name: ${plugin}
version: ${project.version}
main: ${package}
author: Chazza
website: https://felux.io/
softdepend: ["PlaceholderAPI"]

commands:
  blockcommands:
    description: ${plugin} commands
    usage: ""
    aliases: ["bcommands"]

permissions:
  bcommands.add:
    description: Ability to add commands to blocks
  bcommands.reload:
    description: Ability to reload configuration file