name: ${plugin}
version: ${project.version}
main: ${package}
author: Chazza
website: https://plugins.gg

commands:
  blockcommands:
    description: ${plugin} commands
    usage: ""
    aliases: ["bcommands"]